### ISSUE TITLE
Is non-working Federation a docker specific problem?

### ISSUE THREAD

**Issue by maste9** [mplx/docker-pixelfed#5]
I have my instance up and running and after adding the right headers to my apache proxy it is working quite well.
What doesn't seem to work is federation:
* I can't find any other accounts from other instances in search. I only receive "An error occured, results could not be loaded.
Please try again later."
* Interestingly I could find my account on mastodon but don't receive my followrequest. Also mastodon shows no posts of it.

I have adjusted the pixelfed.env 
```
ACTIVITY_PUB=true
REMOTE_FOLLOW=true
AP_REMOTE_FOLLOW=true
ACTIVITYPUB_INBOX=true
AP_INBOX=true
ACTIVITYPUB_SHAREDINBOX=true
```
Is this a problem connected to docker?

Also: Do I have to adjust the APP_KEY variable in the pixelfed.env? Because until now I left the value displayed in the pixelfed.env.example

Thank you in advance!

**Comment by mplx** [comment]
My docker container is based on pixelfed v0.10.9 dating April 2020. As dansup just released v0.10.10 ~1 week ago it's on my schedule to update the container; when I've done so I'll do another try on federation.

**Comment by maste9** [comment]
Can you nevertheless say sth regarding the APP_KEY? Is it valid to use the same key you used in the example-file or do I have to get the key from the 'php artisan key:generate' command?

**Comment by maste9** [comment]
OK, after having my instance running some days 
and following it from a mastodon account 
and having a friend follow me from his instance:

* ~~There are two instances shown in the Admin panel and I could follow back the friend.~~ After I shared two pics with my Mastodon-Account now there are a handfull of followers. And I can see my posts from my Mastodon account. So that seems to work well.
* ~~I can see new posts by him. But still the post count shows 0 on his profile. And I can't see his avatar.~~ I can't see the avatars of any federated account. They try to show the unfindable default.png ... maybe there's a folder missing :thinking: ?

So there's obviously some federation going on ...

**Comment by maste9** [comment]
Aaaand the avatar problem is not an issue but just not implemented in pixelfed https://github.com/pixelfed/pixelfed/issues/1629

So I close this issue.
